name: Generate nxdomains
on:
  workflow_dispatch:

jobs:
  build:
    name: Create nxdomains
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        url:
        - https://someonewhocares.org/hosts/hosts
        - https://github.com/bigdargon/hostsVN/raw/master/hosts
        - https://github.com/DandelionSprout/adfilt/raw/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
        - https://github.com/Perflyst/PiHoleBlocklist/raw/master/SmartTV.txt
        - https://github.com/StevenBlack/hosts/raw/master/data/add.2o7Net/hosts
        - https://github.com/StevenBlack/hosts/raw/master/data/StevenBlack/hosts
        - https://github.com/StevenBlack/hosts/raw/master/data/UncheckyAds/hosts
        - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
        - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
        - https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
        - https://pgl.yoyo.org/as/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
        - https://phishing.army/download/phishing_army_blocklist.txt
        - https://urlhaus.abuse.ch/downloads/hostfile/
        - https://v.firebog.net/hosts/AdguardDNS.txt
        - https://v.firebog.net/hosts/Admiral.txt
        - https://v.firebog.net/hosts/Easylist.txt
        - https://v.firebog.net/hosts/Easyprivacy.txt
        - https://v.firebog.net/hosts/Prigent-Ads.txt
        - https://v.firebog.net/hosts/Prigent-Crypto.txt
        - https://v.firebog.net/hosts/static/w3kbl.txt

    steps:
    - name: Setup filename
      run: echo "filename=$(echo '${{ matrix.url }}' | md5sum | awk '{ print $1}')" >> $GITHUB_ENV

    - name: Build nxdomains
      run: |
        curl -Ls "${{ matrix.url }}" |
        awk '/^\w/ {
            if (match($0, /([a-zA-Z0-9_][a-zA-Z0-9_-]{0,62}\.)+([a-zA-Z][a-zA-Z0-9-]{0,61}[a-zA-Z])/)) {
                host = tolower(substr($0, RSTART, RLENGTH))
                if (system("getent hosts " host " >/dev/null")) print host
            }}' > ${{ env.filename }}.txt

    - name: Archive nxdomains
      uses: actions/upload-artifact@v3
      with:
        retention-days: 1
        name: nxdomains
        path: ${{ env.filename }}.txt

  upload:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout self
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 2

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: nxdomains
        path: temp

    - name: Compile nxdomains
      run: |
        cat temp/*.txt | sort -u > nxdomains.txt
        rm -rf temp/

    - name: Get last commit message
      run: echo "commit_msg=$(git log -1 --pretty=%s)" >> $GITHUB_ENV

    - name: Commit self
      uses: stefanzweifel/git-auto-commit-action@v5.0.0
      with:
        commit_message: ${{ env.commit_msg }}
        commit_options: '--amend --no-edit'
        push_options: '--force'
        skip_fetch: true

  purge:
    needs: build
    uses: filterpaper/scripts/.github/workflows/purge-workflow.yml@main
    with:
      purge-age: 1
      delete-all-completed: false
      delete-all-incomplete: false
